"""Обновление таблицы FolderRelation

Revision ID: 216761ffc9e1
Revises: 891dae3f5746
Create Date: 2025-02-09 14:36:08.751948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "216761ffc9e1"
down_revision: Union[str, None] = "891dae3f5746"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "files", ["id"])
    op.add_column("folder_relations", sa.Column("id", sa.String(), nullable=False))
    op.create_unique_constraint(None, "folder_relations", ["id"])
    op.create_unique_constraint(None, "folders", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "folders", type_="unique")
    op.drop_constraint(None, "folder_relations", type_="unique")
    op.drop_column("folder_relations", "id")
    op.drop_constraint(None, "files", type_="unique")
    # ### end Alembic commands ###
