"""Изменени folder_id на parent_folder

Revision ID: 81a2c573a92e
Revises: cedd55042c2d
Create Date: 2025-03-03 10:53:41.424970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81a2c573a92e"
down_revision: Union[str, None] = "cedd55042c2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("parent_folder", sa.String(), nullable=True))
    op.drop_constraint("files_folder_id_fkey", "files", type_="foreignkey")
    op.create_foreign_key(None, "files", "folders", ["parent_folder"], ["id"])
    op.drop_column("files", "folder_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "files", sa.Column("folder_id", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "files", type_="foreignkey")
    op.create_foreign_key("files_folder_id_fkey", "files", "folders", ["folder_id"], ["id"])
    op.drop_column("files", "parent_folder")
    # ### end Alembic commands ###
